In [10]:
import numpy as np
# numpy 라이브러리를 불러와서 np라는 이름으로 사용하겠다는 의미

In [11]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [12]:
np.array(my_list)
# np.array()는 numpy안에 있는 메소드인 array()를 호출해서 사용하는데
# numpy를 np라는 이름으로 사용할수 있으니, np.array()라는 식으로 사용할 수 있다.

array([1, 2, 3])

In [13]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,10)
# 0부터 시작을 해서 10개의 정수를 뽑아서 배열 형태로 나열해라

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,11,2)
# 0부터 11 사이에 2차이 나는 숫자만 배열

array([ 0,  2,  4,  6,  8, 10])